{
	"version": 1480726750,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/bonecamain-sheet0.png",
		"images/balaomain-sheet0.png",
		"images/botaomain-sheet0.png",
		"images/botaomain-sheet1.png",
		"images/barreirasn1-sheet0.png",
		"images/personagemn1-sheet0.png",
		"images/casan1-sheet0.png",
		"images/barreirasn2-sheet0.png",
		"images/casan2-sheet0.png",
		"images/personagemn2-sheet0.png",
		"images/chegadan1-sheet0.png",
		"images/chegadan2-sheet0.png",
		"images/inicion1-sheet0.png",
		"images/balaon1-sheet0.png",
		"images/balaofinal-sheet0.png",
		"images/parabens-sheet0.png",
		"images/parabenss-sheet0.png",
		"images/setas-sheet0.png",
		"images/voltarinicio-sheet0.png",
		"images/tiledbackground.png",
		"images/background.png",
		"images/backfinal.png",
		"media/labirintomain.m4a",
		"media/labirintomain.ogg",
		"media/balao1l1labirinto.m4a",
		"media/balao1l1labirinto.ogg",
		"media/balao2l1labirinto.m4a",
		"media/balao2l1labirinto.ogg",
		"media/lfinallabirinto.m4a",
		"media/lfinallabirinto.ogg",
		"media/loop_69 som (online-audio-converter.com).ogg",
		"media/loop_37.ogg",
		"media/applause_2 (online-audio-converter.com) (1).ogg",
		"media/applause_2 (online-audio-converter.com).ogg",
		"media/labirintomain(online-audio-converter.com).ogg",
		"media/l1n1(online-audio-converter.com).ogg",
		"media/labirintomain (online-audio-converter.com).ogg",
		"media/labirintol2 (online-audio-converter.com).ogg",
		"media/labirintofinal.m4a",
		"media/labirintofinal.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}